### ISSUE TITLE
New User, Very Confused

### ISSUE THREAD

**Issue by Catkingman** [kinkofer/FightClub5eXML#85]
I have no real experience coding, and have no idea how to actually work this. I think I know the idea behind the merging, I run the code with the sources I want to use listed. But how do I run it? Is there a program I need? Is there something in GitHub that I would use? I made this account specifically and only so that I can use your compendium files, but I have no clue how to make that work. I would very much appreciate some guidance.

Thanks, and sorry for the trouble

**Comment by zcdziura** [comment]
You actually don't need to run any programs to merge anything, unless you want to merge multiple sources into one file (which can make things a bit simpler to handle). Otherwise, you can just download the sources that you want to install found under the "FightClub5eXML/Sources" folder, and import those directly into the app. If you do want to merge multiple sources into one file, then you'll need to download a program called "xsltproc". Assuming that you're using a computer running the Windows operating system, you can follow the instructions (http://www.sagehill.net/docbookxsl/InstallingAProcessor.html)[here] to download that program onto your computer. You can then follow the instructions found at the bottom of the README file to compile the sources you want into a single source file, and import that single source file.

Otherwise, I personally just import the files I want one-at-a-time.

**Comment by dragonahcas** [comment]
http://bit.ly/NewFCXml has it all here.

See also http://dnd.kinkofer.com/
