### ISSUE TITLE
Aarakocra, genasi missing. No elemental evil

### ISSUE THREAD

**Issue by Hoopester** [kinkofer/FightClub5eXML#90]
Why is elemental evil not included in the supplements, and why are aarakocra and genasi excluded from the races is Explorer's guide to wildemount?

Thanks!

**Comment by kinkofer** [comment]
EE will be included in Adventures with Princes of the Apocalypse.
The source we're using avoids duplicates, so races will only appear in their "official" source.

**Comment by Hoopester** [comment]
But aarakocra and genasi are in the Explorer's guide to wildemount. Isn't that their official source? They aren't included at all.

Thanks for your help!

**Comment by kinkofer** [comment]
I can move just the EE races into Supplements. These races list Wildemount as an alternate source, but it doesn't create a separate entry because it would be a duplicate. 

It would take extra work to create a separate duplicate entry per source, but if more people would like to request that we'll take in under consideration.

**Comment by Hoopester** [comment]
OK, thanks for your help!
